version: '3.8'

services:
  db:
    image: mysql:8.0
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=edu_db
      - MYSQL_USER=edu_user
      - MYSQL_PASSWORD=edu_password
      - MYSQL_ROOT_PASSWORD=root_password
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot_password"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  backend:
    build: .
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000 --workers 4 --reload
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "8000:8000"
    environment:
      - DJANGO_ENV=dev
      - DEBUG=True
      - SECRET_KEY=dev-secret-key-change-in-production
      - DB_NAME=edu_db
      - DB_USER=edu_user
      - DB_PASSWORD=edu_password
      - DB_HOST=db
      - DB_PORT=3306
      - REDIS_URL=redis://redis:6379/1
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  celery:
    build: .
    command: celery -A config worker -l info
    volumes:
      - .:/app
    environment:
      - DJANGO_ENV=dev
      - DEBUG=True
      - SECRET_KEY=dev-secret-key-change-in-production
      - DB_NAME=edu_db
      - DB_USER=edu_user
      - DB_PASSWORD=edu_password
      - DB_HOST=db
      - DB_PORT=3306
      - REDIS_URL=redis://redis:6379/1
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - db
      - redis

  celery-beat:
    build: .
    command: celery -A config beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - .:/app
    environment:
      - DJANGO_ENV=dev
      - DEBUG=True
      - SECRET_KEY=dev-secret-key-change-in-production
      - DB_NAME=edu_db
      - DB_USER=edu_user
      - DB_PASSWORD=edu_password
      - DB_HOST=db
      - DB_PORT=3306
      - REDIS_URL=redis://redis:6379/1
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - db
      - redis

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - static_volume:/app/staticfiles:ro
      - media_volume:/app/media:ro
    depends_on:
      - backend

volumes:
  mysql_data:
  redis_data:
  static_volume:
  media_volume:
