# Generated by Django 5.2.7 on 2025-10-09 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(db_index=True, max_length=200)),
                ("slug", models.SlugField(max_length=200, unique=True)),
                ("description", models.TextField(blank=True)),
                ("cover", models.ImageField(blank=True, null=True, upload_to="covers/")),
                ("price", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("is_published", models.BooleanField(db_index=True, default=False)),
            ],
            options={
                "verbose_name": "Book",
                "verbose_name_plural": "Books",
                "db_table": "catalog_book",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Unit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("order", models.PositiveIntegerField(db_index=True, default=0)),
                ("title", models.CharField(max_length=200)),
                (
                    "transcript",
                    models.TextField(blank=True, help_text="Transcript in markdown format"),
                ),
                ("is_free", models.BooleanField(db_index=True, default=False)),
                (
                    "duration_sec",
                    models.PositiveIntegerField(default=0, help_text="Duration in seconds"),
                ),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="units",
                        to="catalog.book",
                    ),
                ),
            ],
            options={
                "verbose_name": "Unit",
                "verbose_name_plural": "Units",
                "db_table": "catalog_unit",
                "ordering": ["book", "order"],
            },
        ),
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "type",
                    models.CharField(
                        choices=[("audio", "Audio"), ("pdf", "PDF"), ("subtitle", "Subtitle")],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("file", models.FileField(upload_to="assets/")),
                ("file_path", models.CharField(blank=True, max_length=500)),
                ("bytes", models.PositiveIntegerField(default=0)),
                ("checksum", models.CharField(blank=True, max_length=64)),
                ("is_protected", models.BooleanField(default=True, help_text="Require signed URL")),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assets",
                        to="catalog.unit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Asset",
                "verbose_name_plural": "Assets",
                "db_table": "catalog_asset",
            },
        ),
        migrations.AddIndex(
            model_name="unit",
            index=models.Index(fields=["book", "order"], name="catalog_uni_book_id_4af946_idx"),
        ),
        migrations.AddIndex(
            model_name="unit",
            index=models.Index(fields=["book", "is_free"], name="catalog_uni_book_id_fc9ef7_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="unit",
            unique_together={("book", "order")},
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(fields=["unit", "type"], name="catalog_ass_unit_id_5293b3_idx"),
        ),
    ]
