# Generated by Django 5.2.7 on 2025-10-09 06:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Attempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "score_raw",
                    models.PositiveIntegerField(default=0, help_text="Number of correct answers"),
                ),
                (
                    "score_pct",
                    models.DecimalField(
                        decimal_places=2, default=0, help_text="Percentage score", max_digits=5
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="catalog.unit",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Attempt",
                "verbose_name_plural": "Attempts",
                "db_table": "quiz_attempt",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("order", models.PositiveIntegerField(db_index=True, default=0)),
                (
                    "type",
                    models.CharField(
                        choices=[("single", "Single Choice"), ("multi", "Multiple Choice")],
                        default="single",
                        max_length=20,
                    ),
                ),
                ("text", models.TextField()),
                (
                    "explanation",
                    models.TextField(blank=True, help_text="Explanation shown after answer"),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="catalog.unit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Question",
                "verbose_name_plural": "Questions",
                "db_table": "quiz_question",
                "ordering": ["unit", "order"],
            },
        ),
        migrations.CreateModel(
            name="Choice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("order", models.PositiveIntegerField(db_index=True, default=0)),
                ("text", models.TextField()),
                ("is_correct", models.BooleanField(default=False)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="choices",
                        to="quiz.question",
                    ),
                ),
            ],
            options={
                "verbose_name": "Choice",
                "verbose_name_plural": "Choices",
                "db_table": "quiz_choice",
                "ordering": ["question", "order"],
            },
        ),
        migrations.CreateModel(
            name="AttemptAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "selected_choices",
                    models.JSONField(default=list, help_text="List of selected choice IDs"),
                ),
                ("is_correct", models.BooleanField(default=False)),
                (
                    "attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="quiz.attempt",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="quiz.question"
                    ),
                ),
            ],
            options={
                "verbose_name": "Attempt Answer",
                "verbose_name_plural": "Attempt Answers",
                "db_table": "quiz_attempt_answer",
            },
        ),
        migrations.AddIndex(
            model_name="attempt",
            index=models.Index(fields=["user", "unit"], name="quiz_attemp_user_id_220201_idx"),
        ),
        migrations.AddIndex(
            model_name="attempt",
            index=models.Index(
                fields=["user", "-created_at"], name="quiz_attemp_user_id_465dd1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(fields=["unit", "order"], name="quiz_questi_unit_id_583ac1_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="question",
            unique_together={("unit", "order")},
        ),
        migrations.AlterUniqueTogether(
            name="choice",
            unique_together={("question", "order")},
        ),
        migrations.AlterUniqueTogether(
            name="attemptanswer",
            unique_together={("attempt", "question")},
        ),
    ]
